stages:
  - build
  - test
  - deploy

cache:
  paths:
    - _build
    - deps

variables:
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  DATABASE_URL: "postgres"
  MIX_ENV: "test"

services:
- name: postgres:12

build:
  stage: build
  image: "docker"
  services:
    - docker:19.03.12-dind
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .

test:
  stage: test
  image: "elixir:1.10"
  script: script/cibuild

deploy:
  stage: deploy
  image: "node:current-alpine"
  script:
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - npm run semantic-release
