stages:
  - prebuild_and_test
  - deploy

cache:
  paths:
    - _build
    - deps

variables:
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  DATABASE_URL: "postgres"
  MIX_ENV: "test"
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376

services:
- name: postgres:12
- name: docker:19.03.12-dind

prebuild:
  stage: prebuild_and_test
  image: docker:19.03.12
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE .

test:
  stage: prebuild_and_test
  image: "elixir:1.10"
  script: script/cibuild

deploy:
  stage: deploy
  image: "circleci/node:14.5"
  script:
    - npm install
    - docker login -u $CI_JOB_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - npx semantic-release
