image: "elixir:1.10"

cache:
  paths:
    - _build
    - deps

variables:
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  DATABASE_URL: "postgres"
  MIX_ENV: "test"

services:
- name: postgres:12

tests:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t gitlab.com/mythic-insight/legendary/legendary .

  script: script/cibuild

build:
  script: npm run semantic-release
