#!/bin/sh

export DOCKER_BUILDKIT=1

docker build \
  --target elixir-builder \
  -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-elixir-builder .

docker build \
  --target asset-builder \
  -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-asset-builder .

docker build \
  -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .

# Push the commit SHA tagged version to registry. We will later choose to tag that as stable
#   if everything passes.
docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-elixir-builder
docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-asset-builder
docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
