#!/bin/sh

set -x
set -e

mix local.hex --force
mix local.rebar --force

script/restore-timestamps

mix deps.get
mix ecto.create
mix ecto.migrate

if [ $1 == 'covered' ]; then
  mix coveralls.json --umbrella
else
  mix test
fi;

script/restore-timestamps
