#!/usr/bin/env node

const fs = require("fs");
const doT = require("dot");
doT.templateSettings = {...doT.templateSettings, strip: false};

const dots = doT.process({path: "./infrastructure_templates"});

var packageText = fs.readFileSync("package.json", {encoding: "utf8"});
var packageConfig = JSON.parse(packageText);

const {version} = packageConfig;

fs.writeFileSync("infrastructure/deployment.yaml", dots.deployment({version: version}));
fs.writeFileSync("infrastructure/service.yaml", dots.service({version: version}));
fs.writeFileSync("infrastructure/ingress.yaml", dots.ingress({version: version}));
