#!/bin/sh

set -x
set -e

FULL_PATH=$(realpath $0)
DIR_PATH=$(dirname $FULL_PATH)

$DIR_PATH/bootstrap

mix deps.get
cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development
(cd .. && mix ecto.migrate)