#!/bin/sh

set -x
set -e

wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
dpkg -i erlang-solutions_2.0_all.deb
apt-get update
apt-get -y install esl-erlang
apt-get -y install elixir
mix local.hex --force
mix local.rebar --force
mix deps.get
mix deps.compile
mix npm.install
mix ecto.create
mix ecto.migrate
npm ci
